namespace Dto.Scryfall;

public class CardSearchBySet
{
    public string? Object { get; set; }
    public string? Id { get; set; }
    public string? OracleId { get; set; }
    public List<int>? MultiverseIds { get; set; }
    public int MtgoId { get; set; }
    public int ArenaId { get; set; }
    public int TcgplayerId { get; set; }
    public int CardmarketId { get; set; }
    public string? Name { get; set; }
    public string? Lang { get; set; }
    public DateTime ReleasedAt { get; set; }
    public string? Uri { get; set; }
    public string? ScryfallUri { get; set; }
    public string? Layout { get; set; }
    public bool HighresImage { get; set; }
    public string? ImageStatus { get; set; }
    public ImageUrisSearchBySet? ImageUris { get; set; }
    public string? ManaCost { get; set; }
    public float Cmc { get; set; }
    public string? TypeLine { get; set; }
    public string? OracleText { get; set; }
    public List<string>? Colors { get; set; }
    public List<string>? ColorIdentity { get; set; }
    public List<string>? Keywords { get; set; }
    public LegalitiesSearchBySet? Legalities { get; set; }
    public List<string>? Games { get; set; }
    public bool Reserved { get; set; }
    public bool Foil { get; set; }
    public bool Nonfoil { get; set; }
    public List<string>? Finishes { get; set; }
    public bool Oversized { get; set; }
    public bool Promo { get; set; }
    public bool Reprint { get; set; }
    public bool Variation { get; set; }
    public string? SetId { get; set; }
    public string? Set { get; set; }
    public string? SetName { get; set; }
    public string? SetType { get; set; }
    public string? SetUri { get; set; }
    public string? SetSearchUri { get; set; }
    public string? ScryfallSetUri { get; set; }
    public string? RulingsUri { get; set; }
    public string? PrintsSearchUri { get; set; }
    public string? CollectorNumber { get; set; }
    public bool Digital { get; set; }
    public string? Rarity { get; set; }
    public string? FlavorText { get; set; }
    public string? CardBackId { get; set; }
    public string? Artist { get; set; }
    public List<string>? ArtistIds { get; set; }
    public string? IllustrationId { get; set; }
    public string? BorderColor { get; set; }
    public string? Frame { get; set; }
    public string? SecurityStamp { get; set; }
    public bool FullArt { get; set; }
    public bool Textless { get; set; }
    public bool Booster { get; set; }
    public bool StorySpotlight { get; set; }
    public int EdhrecRank { get; set; }
    public int PennyRank { get; set; }
    public DateTime Date { get; set; }
    public PricesSearchBySet? Prices { get; set; }
    public RelatedUrisSearchBySet? RelatedUris { get; set; }
    public PricesSearchBySet? PurchaseUris { get; set; }
}