##
## EPITECH PROJECT, 2022
## B-CNA-410-MPL-4-1-groundhog-mehdi.debordes
## File description:
## Makefile
##

NAME    =    groundhog

all:
	cp $(NAME).py $(NAME)
	chmod +x $(NAME)

clean:
	rm -Rf pycache
	rm -Rf $(NAME)

re: clean re