"""init

Revision ID: 8a8b3ba8e2c0
Revises: 
Create Date: 2024-09-16 12:29:49.802924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8b3ba8e2c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('Departure', sa.String(), nullable=True),
    sa.Column('Arrival', sa.String(), nullable=True),
    sa.Column('Duration', sa.Integer(), nullable=True),
    sa.Column('Departure_City', sa.String(), nullable=True),
    sa.Column('Arrival_City', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
