version: "3.9"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
