global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka_server'
    static_configs:
      - targets:
          - broker-1:7003
          - broker-2:7013
          - broker-3:7023
          - controller-1:7103
          - controller-2:7113
          - controller-3:7123

  - job_name: 'jmx_exporter'
    static_configs:
      - targets:
          - jmx-exporter:5556
